# Generated by Django 5.1 on 2024-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppt',
            fields=[
                ('ppt_id', models.AutoField(db_column='PPT_id', primary_key=True, serialize=False)),
                ('ppt_name', models.CharField(blank=True, db_column='PPT_name', max_length=45, null=True)),
                ('ppt_path', models.CharField(blank=True, db_column='PPT_path', max_length=45, null=True)),
                ('ppt_local_path', models.CharField(blank=True, db_column='PPT_local_path', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ppt',
                'managed': False,
            },
        ),
    ]
