-- MySQL Script generated by MySQL Workbench
-- Wed May 29 16:42:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emi_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emi_db` DEFAULT CHARACTER SET utf8 ;
USE `emi_db` ;

-- -----------------------------------------------------
-- Table `emi_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  `User_pw` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_account_UNIQUE` (`User_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emi_db`.`Prompt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`Prompt` (
  `Prompt_id` INT NOT NULL,
  `Prompt_name` VARCHAR(45) NULL,
  `Prompt_content` VARCHAR(45) NULL,
  `User_User_id` INT NOT NULL,
  PRIMARY KEY (`Prompt_id`),
  INDEX `fk_Prompt_User1_idx` (`User_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prompt_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `emi_db`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emi_db`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`Class` (
  `Class_id` INT NOT NULL,
  `Class_name` VARCHAR(45) NULL,
  `User_User_id` INT NOT NULL,
  PRIMARY KEY (`Class_id`),
  INDEX `fk_Class_User1_idx` (`User_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Class_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `emi_db`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emi_db`.`PPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`PPT` (
  `PPT_id` INT NOT NULL,
  `PPT_name` VARCHAR(45) NULL,
  `PPT_path` VARCHAR(45) NULL,
  `Class_Class_id` INT NOT NULL,
  PRIMARY KEY (`PPT_id`),
  INDEX `fk_PPT_Class_idx` (`Class_Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_PPT_Class`
    FOREIGN KEY (`Class_Class_id`)
    REFERENCES `emi_db`.`Class` (`Class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emi_db`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`File` (
  `File_id` INT NOT NULL,
  `File_name` VARCHAR(45) NULL,
  `File_path` VARCHAR(45) NULL,
  `Class_Class_id` INT NOT NULL,
  PRIMARY KEY (`File_id`),
  INDEX `fk_File_Class1_idx` (`Class_Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_File_Class1`
    FOREIGN KEY (`Class_Class_id`)
    REFERENCES `emi_db`.`Class` (`Class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emi_db`.`PPTWord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emi_db`.`PPTWord` (
  `PPTWord_id` INT NOT NULL,
  `PPTWord_page` INT NULL,
  `PPTWord_content` VARCHAR(45) NULL,
  `PPT_PPT_id` INT NOT NULL,
  PRIMARY KEY (`PPTWord_id`),
  INDEX `fk_PPTWord_PPT1_idx` (`PPT_PPT_id` ASC) VISIBLE,
  CONSTRAINT `fk_PPTWord_PPT1`
    FOREIGN KEY (`PPT_PPT_id`)
    REFERENCES `emi_db`.`PPT` (`PPT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
