# Generated by Django 5.1 on 2024-08-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ppt",
            options={"managed": True},
        ),
    ]
