# Generated by Django 5.1 on 2024-08-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppt", "0002_alter_ppt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ppt",
            options={"managed": False},
        ),
    ]
