# Generated by Django 5.1 on 2024-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt", "0004_ppt_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pptword",
            fields=[
                (
                    "pptword_id",
                    models.IntegerField(
                        db_column="PPTWord_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pptword_page",
                    models.IntegerField(
                        blank=True, db_column="PPTWord_page", null=True
                    ),
                ),
                (
                    "pptword_content",
                    models.CharField(
                        blank=True,
                        db_column="PPTWord_content",
                        max_length=10000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pptword",
                "managed": False,
            },
        ),
    ]
