# Generated by Django 5.0.6 on 2024-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(db_column='Class_id', primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, db_column='Class_name', max_length=45, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_name', max_length=45)),
                ('user_account', models.CharField(db_column='User_account', max_length=45, unique=True)),
                ('user_pw', models.CharField(db_column='User_pw', max_length=128)),
                ('is_active', models.IntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
