# Generated by Django 5.0.6 on 2024-07-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "prompt_id",
                    models.IntegerField(
                        db_column="Prompt_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "prompt_name",
                    models.CharField(
                        blank=True, db_column="Prompt_name", max_length=45, null=True
                    ),
                ),
                (
                    "prompt_content",
                    models.CharField(
                        blank=True, db_column="Prompt_content", max_length=45, null=True
                    ),
                ),
            ],
            options={"db_table": "prompt", "managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="User_id", primary_key=True, serialize=False
                    ),
                ),
                ("user_name", models.CharField(db_column="User_name", max_length=45)),
                (
                    "user_account",
                    models.CharField(
                        db_column="User_account", max_length=45, unique=True
                    ),
                ),
                ("user_pw", models.CharField(db_column="User_pw", max_length=45)),
                ("is_active", models.IntegerField()),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "user", "managed": False,},
        ),
    ]
