# Generated by Django 5.0.6 on 2024-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(db_column='Class_id', primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, db_column='Class_name', max_length=45, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.IntegerField(db_column='File_id', primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, db_column='File_name', max_length=45, null=True)),
                ('file_path', models.CharField(blank=True, db_column='File_path', max_length=45, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ppt',
            fields=[
                ('ppt_id', models.IntegerField(db_column='PPT_id', primary_key=True, serialize=False)),
                ('ppt_name', models.CharField(blank=True, db_column='PPT_name', max_length=45, null=True)),
                ('ppt_path', models.CharField(blank=True, db_column='PPT_path', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ppt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pptword',
            fields=[
                ('pptword_id', models.IntegerField(db_column='PPTWord_id', primary_key=True, serialize=False)),
                ('pptword_page', models.IntegerField(blank=True, db_column='PPTWord_page', null=True)),
                ('pptword_content', models.CharField(blank=True, db_column='PPTWord_content', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pptword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('prompt_id', models.IntegerField(db_column='Prompt_id', primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(blank=True, db_column='Prompt_name', max_length=45, null=True)),
                ('prompt_content', models.CharField(blank=True, db_column='Prompt_content', max_length=45, null=True)),
            ],
            options={
                'db_table': 'prompt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_name', max_length=45)),
                ('user_account', models.CharField(db_column='User_account', max_length=45, unique=True)),
                ('user_pw', models.CharField(db_column='User_pw', max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
