# Generated by Django 5.1 on 2024-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ppt",
            fields=[
                (
                    "ppt_id",
                    models.IntegerField(
                        db_column="PPT_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ppt_name",
                    models.CharField(
                        blank=True, db_column="PPT_name", max_length=45, null=True
                    ),
                ),
                (
                    "ppt_path",
                    models.CharField(
                        blank=True, db_column="PPT_path", max_length=45, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ppt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pptword",
            fields=[
                (
                    "pptword_id",
                    models.IntegerField(
                        db_column="PPTWord_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pptword_page",
                    models.IntegerField(
                        blank=True, db_column="PPTWord_page", null=True
                    ),
                ),
                (
                    "pptword_content",
                    models.CharField(
                        blank=True,
                        db_column="PPTWord_content",
                        max_length=10000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pptword",
                "managed": False,
            },
        ),
    ]
